apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: middleware
  namespace: argocd
spec:
  description: Middleware platform - Kafka (Strimzi), Redis operators, UI tools, access control
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
