apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  source:
    repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
    chart: opentelemetry-demo
    targetRevision: 0.40.0
    helm:
      valuesObject:
        # Disable bundled observability backends
        opentelemetry-collector:
          enabled: false
        jaeger:
          enabled: false
        grafana:
          enabled: false
        prometheus:
          enabled: false
        opensearch:
          enabled: false
        
        # Override OTEL_COLLECTOR_NAME to point to TinyOlly collector
        # Components use http://$(OTEL_COLLECTOR_NAME):4317 in their OTLP config
        default:
          env:
            - name: OTEL_COLLECTOR_NAME
              value: agent-collector.tinyolly.svc.cluster.local
  
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
