apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tinyolly-ai-agent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "61"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  source:
    repoURL: 'docker-registry.registry.svc.cluster.local:5000/tinyolly/charts'
    chart: tinyolly-ai-agent
    targetRevision: 0.1.0
    helm:
      valuesObject:
        global:
          namespace: tinyolly-ai-agent
        
        ollama:
          model: tinyllama
          persistence:
            enabled: true
            size: 10Gi
          resources:
            limits:
              cpu: "2000m"
              memory: "4Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
        
        agent:
          image:
            repository: ${ai_agent_image}
            tag: ${ai_agent_tag}
          httpRoute:
            enabled: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: tinyolly-ai-agent
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
