apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: middleware
  source:
    repoURL: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"
    chart: postgres-operator
    targetRevision: 1.14.0
    helm:
      valuesObject:
        # Enable CRD management
        configKubernetes:
          enable_pod_antiaffinity: true
          enable_pod_disruption_budget: true
          watched_namespace: "*"
        # Resource limits
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgres-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
