apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector-config.yaml: |
    # Default TinyOlly OTel Collector Config
    # This is the default configuration template used when no agents are connected.
    # It includes OTLP receivers, OpAMP extension, batch processing, spanmetrics connector,
    # and exports to both debug and OTLP endpoints.

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    extensions:
      opamp:
        server:
          ws:
            endpoint: ws://tinyolly-opamp-server:4320/v1/opamp

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024

    connectors:
      spanmetrics:
        histogram:
          explicit:
            buckets: [1ms, 4ms, 10ms, 20ms, 50ms, 100ms, 200ms, 500ms, 1s, 2s, 5s]
        dimensions:
          - name: http.method
          - name: http.status_code
        dimensions_cache_size: 1000
        aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
        metrics_flush_interval: 15s
        metrics_expiration: 5m

    exporters:
      debug:
        verbosity: detailed
      
      otlp:
        endpoint: "tinyolly-otlp-receiver:4343"
        tls:
          insecure: true

    service:
      extensions: [opamp]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, otlp, spanmetrics]
        
        metrics:
          receivers: [otlp,spanmetrics]
          processors: [batch]
          exporters: [debug, otlp]
        
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, otlp]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyolly-opamp-server
  labels:
    app: tinyolly-opamp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyolly-opamp-server
  template:
    metadata:
      labels:
        app: tinyolly-opamp-server
    spec:
      containers:
      - name: tinyolly-opamp-server
        image: tinyolly-opamp-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4320
          name: websocket
        - containerPort: 4321
          name: http
        env:
        - name: OPAMP_PORT
          value: "4320"
        - name: HTTP_PORT
          value: "4321"
        - name: COLLECTOR_CONFIG_PATH
          value: "/etc/otel-collector-config.yaml"
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-collector-config.yaml
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4321
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 4321
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: otel-collector-config-vol
        configMap:
          name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: tinyolly-opamp-server
spec:
  selector:
    app: tinyolly-opamp-server
  ports:
    - name: websocket
      protocol: TCP
      port: 4320
      targetPort: 4320
    - name: http
      protocol: TCP
      port: 4321
      targetPort: 4321
