apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollyscale-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  source:
    repoURL: "ghcr.io/ot-container-kit/charts"
    chart: redis
    targetRevision: 0.16.8
    helm:
      valuesObject:
        redisStandalone:
          image: quay.io/opstree/redis
          tag: v7.0.15
          imagePullPolicy: IfNotPresent
          serviceType: ClusterIP
          redisSecret: {}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits: {}
        externalConfig:
          enabled: true
          data: |
            maxmemory 256mb
            maxmemory-policy allkeys-lru
        externalService:
          enabled: true
          serviceType: ClusterIP
        redisExporter:
          enabled: true
          image: quay.io/opstree/redis-exporter
          tag: v1.44.0
          imagePullPolicy: IfNotPresent
        storage:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ollyscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
