apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollyscale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  ignoreDifferences:
    - group: opentelemetry.io
      kind: Instrumentation
      name: python-instrumentation
      namespace: ollyscale
      jqPathExpressions:
        - .spec
        - .metadata.annotations
  source:
    repoURL: "${chart_registry}"
    chart: ollyscale
    targetRevision: ${ollyscale_chart_tag}
    helm:
      valuesObject:
        frontend:
          image:
            repository: ${image_registry}/ollyscale
            tag: ${ollyscale_tag}

          resources:
            limits: {}

          httpRoute:
            enabled: false

        webui:
          image:
            repository: ${image_registry}/ollyscale-ui
            tag: ${ollyscale_tag}

          resources:
            limits: {}

          httpRoute:
            enabled: true
            parentRefs:
              - name: cluster-gateway
                namespace: envoy-gateway-system
                sectionName: mgmt-https-listener
            hosts:
              - host: ollyscale.${gateway_dns_suffix}
                path: /
                pathType: PathPrefix

        opampServer:
          image:
            repository: ${image_registry}/opamp-server
            tag: ${opamp_tag}

          resources:
            limits: {}

        otlpReceiver:
          image:
            repository: ${image_registry}/ollyscale
            tag: ${ollyscale_tag}

          resources:
            limits: {}

        redis:
          host: ollyscale-redis
          port: 6379

        # eBPF agent disabled by default - requires real Linux kernel
        # Will NOT work on KIND/macOS/Docker Desktop environments
        # For local development, use OpenTelemetry Operator auto-instrumentation instead
        # ebpfAgent:
        #   enabled: false
        #   config:
        #     # Instrument common development ports
        #     openPorts: "5000,8080,3000,8081"
        #     serviceName: "ebpf-demo"
        #     otlpEndpoint: "http://gateway-collector.ollyscale.svc.cluster.local:4317"

        otelCollector:
          endpoint: http://otel-collector:4318
          protocol: http/protobuf
          tracesEndpoint: http://otel-collector:4318/v1/traces
          metricsEndpoint: http://otel-collector:4318/v1/metrics
          logsEndpoint: http://otel-collector:4318/v1/logs
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ollyscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
