apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry-route
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: 'https://bedag.github.io/helm-charts/'
    chart: raw
    targetRevision: 2.0.2
    helm:
      values: |
        resources:
          -
            apiVersion: gateway.networking.k8s.io/v1
            kind: HTTPRoute
            metadata:
              name: docker-registry
              namespace: registry
            spec:
              parentRefs:
                - name: cluster-gateway
                  namespace: envoy-gateway-system
                  sectionName: mgmt-https-listener
              hostnames:
                - registry.${gateway_dns_suffix}
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  backendRefs:
                    - name: docker-registry
                      port: 5000
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
