apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoyproxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: docker.io
    chart: envoyproxy/gateway-helm
    targetRevision: 1.6.1
    helm:
      valuesObject:
        deployment:
          replicas: 1
          pod:
            tolerations:
            - key: node-role.kubernetes.io/control-plane
              effect: NoSchedule
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
