apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: 'https://bedag.github.io/helm-charts/'
    chart: raw
    targetRevision: 2.0.2
    helm:
      values: |
        resources:
          -
            apiVersion: cert-manager.io/v1
            kind: Certificate
            metadata:
              name: cluster-gateway-cert
              namespace: envoy-gateway-system
            spec:
              dnsNames:
              - '*.apps.${gateway_dns_suffix}'
              - '*.${gateway_dns_suffix}'
              issuerRef:
                kind: ClusterIssuer
                name: cluster-ca-issuer
              privateKey:
                algorithm: ECDSA
                encoding: PKCS8
                size: 256
              secretName: cluster-gateway-cert
              subject:
                organizations:
                - my-org
              usages:
              - server auth
              - client auth
          -
            apiVersion: gateway.envoyproxy.io/v1alpha1
            kind: EnvoyProxy
            metadata:
              name: cluster-gateway
              namespace: envoy-gateway-system
            spec:
              provider:
                type: Kubernetes
                kubernetes:
                  envoyService:
                    type: NodePort
                    patch:
                      value:
                        spec:
                          ports:
                          - name: kafka-port
                            nodePort: ${kafka_nodeport}
                            port: 9094
                            protocol: TCP
                            targetPort: 9094
                          - name: https-port
                            nodePort: ${https_nodeport}
                            port: 9443
                            protocol: TCP
                            targetPort: 9443      
              telemetry:
                metrics:
                  sinks:
                    - type: OpenTelemetry
                      openTelemetry:
                        host: agent-collector.opentelemetry-operator-system.svc.cluster.local
                        port: 4317          
                tracing:
                  samplingRate: 100
                  provider:
                    host: agent-collector.opentelemetry-operator-system.svc.cluster.local
                    port: 4317
                    type: OpenTelemetry
                    serviceName: "envoy-cluster-gateway"
                accessLog:
                  settings:
                    - format:
                        type: JSON
                        json:
                          "@timestamp": "%START_TIME%"
                          "http.request.method": "%REQ(:METHOD)%"
                          "url.path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                          "network.protocol.name": "%PROTOCOL%"
                          "http.response.status_code": "%RESPONSE_CODE%"
                          "envoy.response_flags": "%RESPONSE_FLAGS%"
                          "http.request.body.size": "%BYTES_RECEIVED%"
                          "http.response.body.size": "%BYTES_SENT%"
                          "http.request.duration": "%DURATION%"
                          "client.address": "%REQ(X-FORWARDED-FOR)%"
                          "user_agent.original": "%REQ(USER-AGENT)%"
                          "http.request.id": "%REQ(X-REQUEST-ID)%"
                          "server.address": "%REQ(:AUTHORITY)%"
                          "network.peer.address": "%DOWNSTREAM_REMOTE_ADDRESS%"
                          "upstream.address": "%UPSTREAM_HOST%"
                          "http.response.header.x_envoy_upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
                      sinks:
                        - type: OpenTelemetry
                          openTelemetry:
                            host: agent-collector.opentelemetry-operator-system.svc.cluster.local
                            port: 4317                        
          - 
            apiVersion: gateway.envoyproxy.io/v1alpha1
            kind: EnvoyProxy
            metadata:
              name: management-gateway
              namespace: envoy-gateway-system
            spec:
              provider:
                type: Kubernetes
                kubernetes:
                  envoyService:
                    type: NodePort
                    patch:
                      value:
                        spec:
                          ports:
                          - name: mgmt-https-port
                            nodePort: ${mgmt_https_nodeport}
                            port: 49443
                            protocol: TCP
                            targetPort: 49443
              telemetry: {}
          - 
            apiVersion: gateway.networking.k8s.io/v1
            kind: GatewayClass
            metadata:
              name: cluster-gateway-class
              namespace: envoy-gateway-system
            spec:
              controllerName: gateway.envoyproxy.io/gatewayclass-controller
              parametersRef:
                group: gateway.envoyproxy.io
                kind: EnvoyProxy
                name: cluster-gateway
                namespace: envoy-gateway-system
          -
            apiVersion: gateway.networking.k8s.io/v1
            kind: GatewayClass
            metadata:
              name: management-gateway-class
              namespace: envoy-gateway-system
            spec:
              controllerName: gateway.envoyproxy.io/gatewayclass-controller
              parametersRef:
                group: gateway.envoyproxy.io
                kind: EnvoyProxy
                name: management-gateway
                namespace: envoy-gateway-system
          -
            apiVersion: gateway.networking.k8s.io/v1
            kind: Gateway
            metadata:
              name: management-gateway
              namespace: envoy-gateway-system
            spec:
              gatewayClassName: management-gateway-class
              listeners:
              - name: mgmt-https-listener
                protocol: HTTPS
                port: 49443
                tls:
                  mode: Terminate
                  certificateRefs:
                  - kind: Secret
                    name: cluster-gateway-cert
                    namespace: envoy-gateway-system
                allowedRoutes:
                  namespaces:
                    from: All
          -
            apiVersion: gateway.networking.k8s.io/v1
            kind: Gateway
            metadata:
              name: cluster-gateway
            spec:
              gatewayClassName: cluster-gateway-class
              listeners:
              - name: kafka-listener
                protocol: TLS
                port: 9094
                tls:
                  mode: Passthrough
                allowedRoutes:
                  namespaces:
                    from: All
              - name: https-listener
                protocol: HTTPS
                port: 9443
                tls:
                  mode: Terminate
                  certificateRefs:
                  - kind: Secret
                    name: cluster-gateway-cert
                    namespace: envoy-gateway-system
                allowedRoutes:
                  namespaces:
                    from: All
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
